### PR TITLE
Fix UI deadlock on macOS

### LINKED ISSUE #6: GUI freezes on macOS
On macOS, native deadlocks happen when popping up input dialogs.

I believe the issue has to do with interaction between JavaFX and AWT. Each UI framework has its own dispatch thread in theory, but macOS has special threading requirements with its AppKit thread, meaning that in practice JavaFX and AWT share a single native thread on macOS, leading to problems. See [JDK-8087465](https://bugs.openjdk.java.net/browse/JDK-8087465) for some discussion.

### PR DESCRIPTION
**Pull request by ctrueden**
And improve harvesting of the lifetime axis and time base while we're at it.

Fixes #6.

### CODE REVIEW

**Comment by ctrueden** [comment]
@Xanthorapedia The only remaining issue I noticed is that the FLIMJ UI pops up too small. I'm not sure why my changes resulted in that problem? Speculation: A) maybe I didn't correctly populate something in the `FitParams` and FLIMJ is reacting differently than before as a result? or b) maybe my usage of a JavaFX dialog before the main scene affects JavaFX's behavior somehow?

Initial appearance:

flimj-initial

After maximizing the window:

flimj-maximized

I just noticed a stack trace in the console relating to things happening off the FX user thread. I'll investigate.

**Comment by ctrueden** [comment]
I pushed a fix for one of the exceptions. One more remains:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: No candidate 'flim.fitnull' ops
	at net.imagej.ops.DefaultOpMatchingService.assertCandidates(DefaultOpMatchingService.java:234)
	at net.imagej.ops.DefaultOpMatchingService.findMatch(DefaultOpMatchingService.java:92)
	at net.imagej.ops.DefaultOpMatchingService.findMatch(DefaultOpMatchingService.java:83)
	at net.imagej.ops.OpEnvironment.module(OpEnvironment.java:253)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:136)
	at flimlib.flimj.ui.FitProcessor.updateFit(FitProcessor.java:215)
	at flimlib.flimj.ui.controller.AbstractCtrl.requestUpdate(AbstractCtrl.java:133)
	at flimlib.flimj.ui.controller.SettingsCtrl.lambda$7(SettingsCtrl.java:226)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.control.ChoiceBox.setValue(ChoiceBox.java:336)
	at flimlib.flimj.ui.controller.SettingsCtrl.lambda$12(SettingsCtrl.java:329)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

Seems like something goes wrong checking the value of the current algorithm from the UI?

**Comment by Xanthorapedia** [comment]
Thanks for all the great work!

> @Xanthorapedia The only remaining issue I noticed is that the FLIMJ UI pops up too small. I'm not sure why my changes resulted in that problem? Speculation: A) maybe I didn't correctly populate something in the FitParams and FLIMJ is reacting differently than before as a result? or b) maybe my usage of a JavaFX dialog before the main scene affects JavaFX's behavior somehow?

It seems to be b), but it has something to do with ControlsFX. When rendering the X- and Y-spinners ControlsFX somehow cuts in and tries to decorate them. This triggers a cascade of updates to the top-most `AnchorPane` and [boxes it in a `DecorationPane`](https://github.com/controlsfx/controlsfx/blob/b6af6db83c0c5ddefab740651ff0e2e60a7263e7/controlsfx/src/main/java/org/controlsfx/control/decoration/Decorator.java#L197-L202), whose `layoutX` property is magically set to -width/2 (normally 0 but set to this number if [window centering is turned on](https://github.com/flimlib/flimj-ui/blob/f845d427cb66e72e8eefb4f2e3aabca3bf580392/src/main/java/flimlib/flimj/ui/FitParamsPrompter.java#L105)). When calculating the preferred window size, [the negative offset cuts the width in half](https://github.com/openjdk/jfx/blob/a4f3150541d733c48a4963b0f934f1a89c095f5c/modules/javafx.graphics/src/main/java/javafx/scene/Scene.java#L1753), give or take some size negotiation between children components. I have lost patience digging though... :confused:

My fix is simply setting the scene off the table and reveal it later. Please let me know if that works.

> I pushed a fix for one of the exceptions. One more remains:

You are right that the initial `fp.updateFit()` relies on `fp.refreshControllers()` to provide the algorithm name. I have taken them out of threading because `initFX()` is already on the user thread.

**Comment by ctrueden** [comment]
@Xanthorapedia Thanks for working on this!

Unfortunately, I was seeing a deadlock again on macOS with 562b7aa2857c3d1581b3276ed45d96ce9e92f82c (`FLIMJCommand: Refresh UI from FX user thread.`):

<details>

```
"AWT-EventQueue-0" #14 prio=6 os_prio=31 tid=0x00007fd0a2483800 nid=0x13b0b runnable [0x000070000e3e0000]
   java.lang.Thread.State: RUNNABLE
	at sun.lwawt.macosx.CWrapper$NSWindow.isKeyWindow(Native Method)
	at sun.lwawt.macosx.CPlatformWindow.lambda$setVisible$4(CPlatformWindow.java:597)
	at sun.lwawt.macosx.CPlatformWindow$$Lambda$106/214768579.run(Unknown Source)
	at sun.lwawt.macosx.CFRetainedResource.execute(CFRetainedResource.java:134)
	at sun.lwawt.macosx.CPlatformWindow.setVisible(CPlatformWindow.java:589)
	at sun.lwawt.LWWindowPeer.setVisibleImpl(LWWindowPeer.java:249)
	at sun.lwawt.LWComponentPeer.setVisible(LWComponentPeer.java:765)
	at java.awt.Component.show(Component.java:1648)
	- locked <0x00000006c0002e20> (a java.awt.Component$AWTTreeLock)
	at java.awt.Window.show(Window.java:1042)
	at java.awt.Component.show(Component.java:1681)
	at java.awt.Component.setVisible(Component.java:1633)
	at java.awt.Window.setVisible(Window.java:1014)
	at org.scijava.ui.swing.console.SwingConsolePane$1.run(SwingConsolePane.java:121)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at org.scijava.thread.DefaultThreadService$$Lambda$7/1703009290.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"JavaFX Application Thread" #12 daemon prio=5 os_prio=31 tid=0x00007fd0a2c1f800 nid=0x307 waiting for monitor entry [0x00007ffeed0dc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Container.isParentOf(Container.java:3274)
	- waiting to lock <0x00000006c0002e20> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.clearCurrentFocusCycleRootOnHide(Container.java:3311)
	at java.awt.Component.hide(Component.java:1708)
	at javax.swing.JComponent.hide(JComponent.java:5565)
	at java.awt.Component.show(Component.java:1683)
	at java.awt.Component.setVisible(Component.java:1633)
	at javax.swing.JComponent.setVisible(JComponent.java:2645)
	at flimlib.flimj.ui.FLIMJCommand.initFX(FLIMJCommand.java:90)
	at flimlib.flimj.ui.FLIMJCommand.lambda$run$0(FLIMJCommand.java:55)
	at flimlib.flimj.ui.FLIMJCommand$$Lambda$198/1237107521.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$199/1953015679.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$197/1812363767.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

</details>

It was a simpler problem this time, at least, since only the two UI threads were involved.

Same problem with f61cdba26f97a38c93ce7967fe1a1e35c916b3d4 (`FLIMJCommand: Reorder scene loading`).

Deleting `Reorder scene loading`, but leaving `Refresh UI from FX user thread`, there is no deadlock—the dialog pops successfully, but the main FLIMJ window is still incorrectly sized afterward.

In the aforementioned code, there were still Swing steps (e.g. `frame.setVisible(true)`) being done on the JavaFX thread, which does not work correctly on macOS.

I did some experiments, and settled on f171eb83fa9314024a17ed6bce40e405c3c58b41 to fix the problems. It is fully working on my macOS system now; @Xanthorapedia please test on your system too! Thanks.

**Review by Xanthorapedia — APPROVED** [review]

**Pull request merged**
